#!/bin/bash
set -eu

cd "$(dirname "$0")"

source ~/dlang/dmd-2.094.2/activate

test -f build.local && source build.local

flags=(
	-m64
	-g
	-Isrc
	-Ilib
	-L-lcurl
	-L-lsqlite3
#	-debug
#	-debug=ASOCKETS
#	-version=LIBEV
)

if false # [[ -f /usr/lib/libssl.so.1.0.0 ]]
then
	flags+=(
		-L/usr/lib/libssl.so.1.0.0
		-L/usr/lib/libcrypto.so.1.0.0
	)
else
	flags+=(
		-L-lssl
		-L-lcrypto
	)
fi

progs=()

for arg in "$@"
do
	if [[ "$arg" == -* ]]
	then
		flags+=("$arg")
	else
		progs+=("$arg")
	fi
done

if [[ "${#progs[@]}" -eq 0 ]]
then
	for fn in $(find src/dfeed/progs -name '*.d')
	do
		name=$(realpath --relative-to=src/dfeed/progs "$fn")
		progs+=("${name%.d}")
	done
fi

for prog in "${progs[@]}"
do
	echo "Rebuilding $prog..."
	rdmd --build-only -of"${prog//\//-}" "${flags[@]}" "src/dfeed/progs/$prog.d"
	echo OK.
done
echo Rebuilding resources...
make -s
echo Done.
